name: fashion_trend_forecasting-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas
  - numpy
  - scikit-learn
  - pyyaml
  - joblib
  - flask
  - gunicorn
  - pytest
  - streamlit
  - matplotlib
  - seaborn
  - pip:
      - sentence_transformers
      - pyampute
      - rapidfuzz
